apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    kompose.image-pull-policy: Always
spec:
  containers:
    - image: busybox:latest
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
      name: busybox
  restartPolicy: Always
