version: "3"

services:

  redis-master:
    image: k8s.gcr.io/redis:e2e
    ports:
      - "6379"

  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer
  
  busybox-dimko:
    pull: Always
    image: ubuntu:18.04
    labels:
      kompose.image-pull-policy: Always
    command: tail -F anything